"""Added year_founded to Company25

Revision ID: 43071f660afc
Revises: b635e50d16aa
Create Date: 2022-06-26 11:24:45.483812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43071f660afc'
down_revision = 'b635e50d16aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('group_user_fkey', 'group', type_='foreignkey')
    op.drop_column('group', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('group_user_fkey', 'group', 'user', ['user'], ['id'])
    # ### end Alembic commands ###
