"""Added year_founded to Company252453

Revision ID: 6b767d82cbb2
Revises: 85bd63769c56
Create Date: 2022-06-26 16:17:36.949817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b767d82cbb2'
down_revision = '85bd63769c56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_subscriber', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_subscriber', 'date')
    # ### end Alembic commands ###
