"""Added year_founded to Company25245

Revision ID: 85bd63769c56
Revises: 0cc41ae17759
Create Date: 2022-06-26 15:09:26.247616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85bd63769c56'
down_revision = '0cc41ae17759'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_event_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_event_date')
    # ### end Alembic commands ###
