"""Added year_founded to Company23

Revision ID: 997ddbc05a8d
Revises: 52a8a1a9d1bf
Create Date: 2022-06-22 22:24:51.893299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997ddbc05a8d'
down_revision = '52a8a1a9d1bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'group', 'user', ['user'], ['id'])
    op.create_foreign_key(None, 'group', 'user', ['owner'], ['id'])
    op.create_foreign_key(None, 'message', 'user', ['sender'], ['id'])
    op.create_foreign_key(None, 'message', 'group', ['group'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_constraint(None, 'group', type_='foreignkey')
    # ### end Alembic commands ###
