"""Added year_founded to Company5

Revision ID: d86c9cbd24fd
Revises: 9fafd3f66902
Create Date: 2022-06-22 22:08:55.747363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86c9cbd24fd'
down_revision = '9fafd3f66902'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
