"""Added year_founded to Company10

Revision ID: f9f9b191450f
Revises: 997ddbc05a8d
Create Date: 2022-06-25 20:15:43.313360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9f9b191450f'
down_revision = '997ddbc05a8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    op.add_column('message', sa.Column('recipient', sa.Integer(), nullable=True))
    op.drop_constraint('message_group_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'user', ['recipient'], ['id'])
    op.drop_column('message', 'group')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('group', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_group_fkey', 'message', 'group', ['group'], ['id'])
    op.drop_column('message', 'recipient')
    op.create_table('notes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='notes_pkey')
    )
    # ### end Alembic commands ###
